import { LightningElement, track } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import getSettings from '@salesforce/apex/DeliveryHubSettingsController.getSettings';
import saveAiSettings from '@salesforce/apex/DeliveryHubSettingsController.saveAiSettings';

export default class AiSettingsCard extends LightningElement {
    @track aiSuggestionsEnabled = false;
    @track autoGenerateDescriptions = false;
    @track aiEstimationEnabled = false;
    @track hasValidOpenAIKey = false; // Tracks if the OpenAI key is tested and valid
    
    @track isLoading = true;

    // --- REPLACED @wire WITH IMPERATIVE CALL ---
    connectedCallback() {
        this.loadSettings();
    }

    async loadSettings() {
        try {
            const data = await getSettings();
            if (data) {
                this.aiSuggestionsEnabled = data.aiSuggestionsEnabled || false;
                this.autoGenerateDescriptions = data.autoGenerateDescriptions || false;
                this.aiEstimationEnabled = data.aiEstimationEnabled || false;
                // Set the dependency flag based on the OpenAI API test status
                this.hasValidOpenAIKey = data.openAiApiTested || false;
            }
        } catch (error) {
            this.showToast('Error Loading AI Settings', error.body?.message || error.message, 'error');
        } finally {
            this.isLoading = false;
        }
    }

    async handleSettingChange(event) {
        const { name, checked } = event.target;
        const originalValue = this[name];

        // --- VALIDATION STEP ---
        // Check if user is trying to ENABLE the main feature without a valid key
        if (name === 'aiSuggestionsEnabled' && checked && !this.hasValidOpenAIKey) {
            
            this.showToast(
                'Configuration Required',
                'Please complete and test your OpenAI API configuration before enabling AI features.',
                'error'
            );
            // Revert UI change
            event.target.checked = false;
            return;
        }

        // Update the state based on the changed input
        this[name] = checked;

        // Cascade changes if the main toggle is modified
        if (name === 'aiSuggestionsEnabled') {
            this.autoGenerateDescriptions = checked;
            this.aiEstimationEnabled = checked;
        }

        this.isLoading = true;

        try {
            await saveAiSettings({
                suggestions: this.aiSuggestionsEnabled,
                descriptions: this.autoGenerateDescriptions,
                estimation: this.aiEstimationEnabled
            });
        } catch (error) {
            this.showToast('Error Saving AI Settings', error.body?.message || error.message, 'error');
            // Revert the change on a save error
            this[name] = originalValue;
             if (name === 'aiSuggestionsEnabled') {
                this.autoGenerateDescriptions = originalValue;
                this.aiEstimationEnabled = originalValue;
            }
        } finally {
            this.isLoading = false;
        }
    }

    showToast(title, message, variant) {
        this.dispatchEvent(new ShowToastEvent({ title, message, variant }));
    }

    // Getters to control the disabled state of the sub-feature toggles
    get isAutoDescriptionsDisabled() {
        return !this.aiSuggestionsEnabled;
    }

    get isAiEstimationDisabled() {
        return !this.aiSuggestionsEnabled;
    }
}